version: "3.4"

services:
  mysql:
    platform: linux/x86_64 # require for m1.
    image: mysql:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: homecooking
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: Password1!
    volumes:
      - ./mysql-data:/var/lib/mysql/
      - ./mysql_create:/docker-entrypoint-initdb.d/
    restart: always
    ports:
      - "3306:3306"
