version: '3.4'

services:
  pgsql:
    image: postgres:latest
    environment:
      POSTGRES_DB: homecooking
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: Password1!
    volumes:
      - ./sql_data:/var/lib/postgresql/data
      - ./lib/sql_create:/docker-entrypoint-initdb.d/
    restart: always
    ports:
      - '5432:5432'

  home-cooking-fastify:
    depends_on:
      - pgsql
    image: ${DOCKER_REGISTRY-}home-cooking-fastify:dev
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - '5000:5000'
    environment:
      IS_DOCKER: 1

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #   - ./nginx/nginx.conf:/tmp/default.conf
    depends_on:
      - home-cooking-fastify
    ports:
      - '5001:80'
    # environment:
    #   - NGINX_PORT=8080
    # command: /bin/bash -c "envsubst '$$NGINX_PORT' < /tmp/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  # docker run --name home-cooking-fastify -it -p 5000:5000 home-cooking-fastify:dev /bin/bash
