GET http://localhost:5000/users

###

POST http://localhost:5000/users/add HTTP/1.1
Content-Type: text/plain
Content-Length: 27

{ 
    "userName": "Sean"
}

###

GET http://localhost:5000/recipes

###

POST http://localhost:5000/recipes/add HTTP/1.1
Content-Type: text/plain
Content-Length: 27

{ 
    "userId": 1, 
    "name": "Pasta and Sausage",  
    "description": "Nice food",
    "method": "Make the pasta"
}